site_name: Supermat Documentation
repo_url: https://github.com/rishikreddy1717/supermat
repo_name: supermat
edit_uri: edit/main/docs/

theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-2
        name: Switch to light mode
  icon:
    repo: simple/github
    edit: material/pencil
    view: material/eye
  features:
    - navigation.path
    - navigation.top
    - navigation.instant

plugins:
  - search
  - autorefs
  - mkdocstrings
  - literate-nav:
      nav_file: SUMMARY.md
      tab_length: 2
  - git-authors:
      strict: false
      fallback_to_empty: true
      exclude:
        - reference/
  - table-reader
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      fallback_to_build_date: true
  - gen-files:
      scripts:
        - docs/auto_generate_refs.py
  - section-index

markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - tables
  - mdx_math
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js

extra_css:
  - css/code_select.css
