name: Publish docs via GitHub Pages 
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Setup Poetry Dynamic Version
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "poetry"
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install Python MkDocs Dependencies
        run: |
          poetry install --only docs
      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
